calcula_apagones:
  outputs:
    prod:
      type: duckdb
      path: 'databases/calcula_apagones.db'
      extensions:
        - httpfs
      attach:
        - path: "https://numeros-luzpr.com/databases/regions_without_service_cache.db"
          read_only: true
  target: prod