name: Project Setup

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
      DatawarehouseType:
        type: choice
        required: true
        description: DWH type
        options: 
        - postgres
        - snowflake
        - redshift
        - bigquery
      tags:
        description: 'Set up the project to run on GH Actions'
        required: false
        type: boolean

jobs:
  project_setup:
    runs-on: ubuntu-latest

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"

      - name: install requirements
        run: pip install -q -r requirements.txt

      - name: Add prod target to profiles.yml
        run: "python update_profile_with_prod.py ${{ github.event.inputs.DatawarehouseType }}"

      - name: Create PR with updated profiles.yml file
        uses: peter-evans/create-pull-request@v5
        with:
          title: "Add prod target to profiles.yml"
          commit-message: "Add prod target to profiles.yml"
          branch: "add-prod-target"
          base: "main"
          token: ${{ secrets.WORKFLOW_TOKEN }}
          body: |
            This pull request adds a new target called "prod" to the `profiles.yml` file
