name: Scheduled dbt run - prod

on:
  schedule:
    - cron: "*/12 * * * *"
  workflow_dispatch:
        
jobs:
  dbt_scheduled_run:
    runs-on: ubuntu-latest
    env:
      HOST: ${{ secrets.HOST }}
      DATABASE: ${{ secrets.DATABASE }}
      USERNAME: ${{ secrets.PROD_USERNAME }}
      PASSWORD: ${{ secrets.PROD_PASSWORD }}
      PORT: ${{ secrets.PORT }}
      SCHEMA: ${{ secrets.PROD_SCHEMA }}
      AWS_DEFAULT_REGION: 'auto'
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      DUCKDB_S3_ENDPOINT: ${{ secrets.DUCKDB_S3_ENDPOINT }}

    steps:
      - uses: "actions/checkout@main"

      - name: install requirements
        run: pip install -q -r requirements.txt

      - name: dbt deps
        run: |
          cd calcula_apagones 
          dbt deps

      - name: Get manifest.json from gh-pages branch
        run: |
          ./get_manifest.sh
        
      - name: dbt build
        run: |
          cd calcula_apagones
          mkdir databases 
          dbt build
          dbt docs generate

      - name: Push new documentation to GH Pages
        run: |
          ./save_and_publish_docs.sh
